[project]
org-name= "ballerinax"
license= ["Apache-2.0"]
authors = ["Ballerina"]
version= "0.99.0"
keywords = ["aws.sqs", "Amazon", "SQS", "Ballerina", "connector", "client"]
repository = "https://github.com/ballerina-platform/module-ballerinax-aws.sqs"
