[project]
org-name= "ballerinax"
license= ["Apache-2.0"]
authors = ["Ballerina"]
version= "0.11.0"
keywords = ["amazonsqs", "Amazon", "SQS", "Ballerina", "connector", "client"]
repository = "https://github.com/ballerina-platform/module-amazonsqs"
