name: Deployment

on: [release]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Ballerina Build
              uses: ballerina-platform/ballerina-action/@master
              with:
                  args:
                      build -c --skip-tests
              env:
                  ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
                  SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
                  REGION: ${{ secrets.REGION }}
                  ACCOUNT_NUMBER: ${{ secrets.ACCOUNT_NUMBER }}
            - name: Ballerina Push
              uses: ballerina-platform/ballerina-action/@master
              with:
                  args:
                      push
              env:
                  BALLERINA_CENTRAL_ACCESS_TOKEN: ${{ secrets.BALLERINA_CENTRAL_ACCESS_TOKEN }}
